location = /pyro-inventory {
    return 308 /pyro-inventory/;
}

location /pyro-inventory/ {
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $upstream http://pyro_inventory:8002;
        rewrite ^/pyro-inventory/(.*)$ /$1 break;
        proxy_pass $upstream;        

        proxy_http_version 1.1;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Prefix /pyro-inventory;

        proxy_connect_timeout 10s;
        proxy_read_timeout    60s;
        proxy_send_timeout    60s;

        proxy_buffer_size        16k;
        proxy_buffers            4 16k;
        proxy_busy_buffers_size  32k;
       
    }