-- ====================================================================
-- RESTORE SCRIPT FOR PHASE 18 TEST DATA PREPARATION
-- Generated by prepare_phase18_test_data.py
-- ====================================================================

-- 1. RESTORE ORACLE CAF_ADMIN.BCD
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2864984 WHERE GSMNUMBER = '6826185828' AND CAF_SERIAL_NO = 'BEC4018706' AND CIRCLE_CODE = 2;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2868906 WHERE GSMNUMBER = '8988076675' AND CAF_SERIAL_NO = 'BEC4024252' AND CIRCLE_CODE = 55;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2864729 WHERE GSMNUMBER = '8988246286' AND CAF_SERIAL_NO = 'BEC4015117' AND CIRCLE_CODE = 55;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2879904 WHERE GSMNUMBER = '7380036199' AND CAF_SERIAL_NO = 'BEC4037604' AND CIRCLE_CODE = 56;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2977829 WHERE GSMNUMBER = '6375250315' AND CAF_SERIAL_NO = 'BEC4022792' AND CIRCLE_CODE = 59;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2980470 WHERE GSMNUMBER = '7317297365' AND CAF_SERIAL_NO = 'BEC4015231' AND CIRCLE_CODE = 60;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2864874 WHERE GSMNUMBER = '8278247741' AND CAF_SERIAL_NO = 'BEC4017338' AND CIRCLE_CODE = 61;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2978646 WHERE GSMNUMBER = '7248011700' AND CAF_SERIAL_NO = 'BEC4023891' AND CIRCLE_CODE = 62;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2845429 WHERE GSMNUMBER = '7579017985' AND CAF_SERIAL_NO = 'BEC3988493' AND CIRCLE_CODE = 64;
UPDATE CAF_ADMIN.BCD SET FRC_FLOW_STATUS = 'RQ', FRC_REQID = 2869729 WHERE GSMNUMBER = '9419276386' AND CAF_SERIAL_NO = 'BEC4022891' AND CIRCLE_CODE = 65;
COMMIT;

-- 2. RESTORE POSTGRESQL cos_bcd
UPDATE public.cos_bcd SET gsmnumber = '', circle_code = NULL, de_csccode = '9188767335', frc_plan_name = '', frc_plan_code = '', frc_category_code = '', frc_ctopup_number = '', frc_ctopup_number_mpin = '' WHERE caf_serial_no = 'E5486350929';
UPDATE public.cos_bcd SET gsmnumber = '00000000', circle_code = '50', de_csccode = 'TESTDSA145361', frc_plan_name = '', frc_plan_code = '', frc_category_code = '', frc_ctopup_number = '', frc_ctopup_number_mpin = '' WHERE caf_serial_no = 'BEC0465779';
UPDATE public.cos_bcd SET gsmnumber = '00000000', circle_code = '50', de_csccode = 'TESTDSA145361', frc_plan_name = '', frc_plan_code = '', frc_category_code = '', frc_ctopup_number = '', frc_ctopup_number_mpin = '' WHERE caf_serial_no = 'BEC0466026';
UPDATE public.cos_bcd SET gsmnumber = '0000000000', circle_code = '50', de_csccode = 'TESTDSA145361', frc_plan_name = '', frc_plan_code = '', frc_category_code = '', frc_ctopup_number = '', frc_ctopup_number_mpin = '' WHERE caf_serial_no = 'BEC0448253';
UPDATE public.cos_bcd SET gsmnumber = '0000000000', circle_code = '50', de_csccode = 'TESTDSA145361', frc_plan_name = 'PREPAID-FRC-1', frc_plan_code = '1002000', frc_category_code = '1001', frc_ctopup_number = '9447666700', frc_ctopup_number_mpin = '123456' WHERE caf_serial_no = 'BEC0401942';

-- 3. RESTORE POSTGRESQL cos_bcd_dkyc
UPDATE public.cos_bcd_dkyc SET gsmnumber = '9495950452', caf_serial_no = 'BDC0000090', circle_code = '50', de_csccode = 'KETVMCTOCSC', tariff_plan = 'FRC-1', parent_ctopup_number = '9497802714', mpin = '123456' WHERE id = 48;
UPDATE public.cos_bcd_dkyc SET gsmnumber = '9447470864', caf_serial_no = 'BDC0000091', circle_code = '50', de_csccode = 'KECLTKPTCSR', tariff_plan = 'FRC-1', parent_ctopup_number = '9495656279', mpin = '123456' WHERE id = 49;
UPDATE public.cos_bcd_dkyc SET gsmnumber = '9482102662', caf_serial_no = 'BDC0000092', circle_code = '53', de_csccode = 'KT01115', tariff_plan = 'FRC-249', parent_ctopup_number = '9448622220', mpin = '123456' WHERE id = 50;
UPDATE public.cos_bcd_dkyc SET gsmnumber = '8300289728', caf_serial_no = 'BDC0000093', circle_code = '54', de_csccode = 'TN10106', tariff_plan = 'FRC-1', parent_ctopup_number = '7598058579', mpin = '123456' WHERE id = 51;
UPDATE public.cos_bcd_dkyc SET gsmnumber = '8985729425', caf_serial_no = 'BDC0000094', circle_code = '41', de_csccode = 'AP0748', tariff_plan = 'FRC-249', parent_ctopup_number = '9491238422', mpin = '123456' WHERE id = 52;

-- 4. RESTORE POSTGRESQL frc_plan_table
DELETE FROM public.frc_plan_table WHERE plan_code = '1002000' AND circle_code = '2';
UPDATE public.frc_plan_table SET end_date = '2026-09-12' WHERE plan_code = '1002000' AND circle_code IN ('55', '56', '59', '60', '61', '62', '64', '65');
UPDATE public.frc_plan_table SET end_date = '2026-01-31' WHERE plan_code = '1002000' AND circle_code = '9999';
