-- public.cos_bcd definition

-- Drop table

-- DROP TABLE public.cos_bcd;

CREATE TABLE public.cos_bcd (
	de_csccode varchar(150) NULL,
	de_username varchar(150) NULL,
	dateallottment timestamp(6) NULL,
	gsmnumber varchar(150) NULL,
	simnumber varchar(150) NULL,
	caf_serial_no varchar(30) NULL,
	connection_type numeric(2) NULL,
	"name" varchar(150) NULL,
	middle_name varchar(150) NULL,
	last_name varchar(150) NULL,
	f_h_name varchar(300) NULL,
	gender varchar(24) NULL,
	date_of_birth timestamp(6) NULL,
	local_addr_hno varchar(600) NULL,
	local_addr_street varchar(600) NULL,
	local_addr_locality varchar(600) NULL,
	local_addr_city varchar(150) NULL,
	local_addr_state varchar(90) NULL,
	local_addr_pin numeric(6) NULL,
	perm_addr_hno varchar(600) NULL,
	perm_addr_street varchar(600) NULL,
	perm_addr_locality varchar(600) NULL,
	perm_addr_city varchar(150) NULL,
	perm_addr_state varchar(150) NULL,
	perm_addr_pin numeric(6) NULL,
	billing_address varchar(750) NULL,
	customer_type varchar(300) DEFAULT 'individual'::character varying NULL,
	nationality varchar(60) NULL,
	country varchar(90) NULL,
	visa_expiry_date timestamp(6) NULL,
	email varchar(150) NULL,
	photo_id_doc numeric(3) NULL,
	photo_id_sno varchar(75) NULL,
	photo_id_issue_date timestamp(6) NULL,
	photo_id_issue_auth varchar(150) NULL,
	photo_id_issue_place varchar(75) NULL,
	address_id_doc numeric(3) NULL,
	address_id_sno varchar(150) NULL,
	address_id_issue_date timestamp(6) NULL,
	address_id_issue_auth varchar(150) NULL,
	address_id_issue_place varchar(150) NULL,
	distinct_operators numeric(2) NULL,
	other_connection_det varchar(450) NULL,
	services varchar(300) NULL,
	alternate_contact_no numeric(10) NULL,
	bsnl_telno varchar(75) NULL,
	other_telno varchar(75) NULL,
	profession varchar(60) NULL,
	organisation varchar(90) NULL,
	mar_status varchar(60) NULL,
	qualification varchar(69) NULL,
	imsi_old numeric(19) NULL,
	pan_gir_uid varchar(60) NULL,
	local_ref varchar(750) NULL,
	local_ref_contact varchar(36) NULL,
	plan_code numeric NULL,
	levelno numeric(10) NULL,
	benefitvalidity timestamp(6) NULL,
	servicetax numeric(19, 4) NULL,
	plancharge numeric(19, 4) NULL,
	levelamount numeric(10) NULL,
	advancerent numeric(10) NULL,
	totalamount numeric(19, 4) NULL,
	commission numeric(10) NULL,
	netamount numeric(10) NULL,
	footnoteremarks1 varchar(1800) NULL,
	receiptno varchar(150) NULL,
	stdpco varchar(150) NULL,
	cust_unique_id varchar(150) NULL,
	caf_avail varchar(60) NULL,
	caf_rejected bpchar(3) NULL,
	caf_recd_date timestamp(6) NULL,
	intd_flag numeric(3) NULL,
	checked_yn bpchar(3) NULL,
	flag numeric NULL,
	flag_date timestamp(6) NULL,
	msc varchar(90) NULL,
	in_plan_id varchar(60) NULL,
	in_code varchar(60) NULL,
	dummy_sim varchar(3) NULL,
	og_enable varchar(3) NULL,
	dnc varchar(3) NULL,
	act_type varchar(150) NULL,
	paymenttype varchar(3) NULL,
	dd_details varchar(300) NULL,
	bank_details varchar(450) NULL,
	submitted_date timestamp(6) NULL,
	tariff_plan_app varchar(90) NULL,
	vas_app varchar(90) NULL,
	tariff_plan_gprs_mms varchar(60) NULL,
	sales_channel_id numeric NULL,
	subscr_id numeric NULL,
	upc_code varchar(30) NULL,
	prev_optr varchar(60) NULL,
	ruim_no varchar(60) NULL,
	order_id varchar(60) NULL,
	level1date timestamp(6) NULL,
	level2date timestamp(6) NULL,
	completed_by varchar(90) NULL,
	circle_code numeric(3) NULL,
	activation_csccode varchar(60) NULL,
	activation_username varchar(60) NULL,
	activation_mobileno varchar(36) NULL,
	activation_date timestamp(6) NULL,
	hlr_init_act_date timestamp(6) NULL,
	tele_ver_agent_code varchar(60) NULL,
	tele_ver_date timestamp(6) NULL,
	tele_ver_remarks varchar(300) NULL,
	hlr_final_act_date timestamp(6) NULL,
	activation_status varchar(6) NULL,
	activation_remarks varchar(900) NULL,
	hlr_init_sent_date timestamp(6) NULL,
	hlr_final_sent_date timestamp(6) NULL,
	ss_cug_id numeric(6) NULL,
	account_type varchar(60) NULL,
	connection_no numeric(6) NULL,
	category_code numeric(6) NULL,
	product_code numeric(7) NULL,
	converted numeric(1) NULL,
	uid_no varchar(12) NULL,
	gstin_no varchar(150) NULL,
	gst_registered_address varchar(600) NULL,
	gst_state_code varchar(60) NULL,
	gst_pin numeric(20) NULL,
	blg_gst_updt timestamp(6) NULL,
	status varchar(30) NULL,
	ssa_code varchar(30) NULL,
	pos_mobile_no varchar(300) NULL,
	package_id varchar(30) NULL,
	tvplan_act_date timestamp(6) NULL,
	tvplan_act_remarks varchar(600) NULL,
	tvplan_deact_date timestamp(6) NULL,
	tvplan_deact_remarks varchar(600) NULL,
	account_no varchar(45) NULL,
	doptr varchar(30) NULL,
	remarks varchar(600) NULL,
	alternate_contact_own varchar(30) NULL,
	tracking_id numeric(10) NULL,
	sdp_activation_status varchar(30) NULL,
	sdp_activation_date timestamp(6) NULL,
	full_mnp varchar(6) NULL,
	account_category numeric(3) NULL,
	gateway_date timestamp(6) NULL,
	doptr_circle_code varchar(6) NULL,
	billing_mnp_date timestamp(6) NULL,
	mnp_edit_date timestamp(6) NULL,
	is_bill_submit numeric NULL,
	msisdn_type numeric NULL,
	sim_type numeric NULL,
	cmf_account_category numeric NULL,
	cmf_bill_state varchar(300) NULL,
	cmf_bill_fmt_opt numeric NULL,
	cmf_bill_disp_meth numeric NULL,
	cmf_rate_class_default numeric NULL,
	cmf_exrate_class numeric NULL,
	cmf_mkt_code numeric NULL,
	cmf_vip_code numeric NULL,
	cmf_acct_seg_id numeric NULL,
	cmf_bill_period varchar(300) NULL,
	zone_element_id numeric NULL,
	invs_saleschannel_id numeric NULL,
	print_service_center_id numeric NULL,
	imsi varchar(60) NULL,
	primary_talk_value numeric(10) NULL,
	freebies varchar(60) NULL,
	simstate varchar(45) NULL,
	emf_config_id numeric NULL,
	ins_usr varchar(300) NULL,
	om_remarks varchar(3000) NULL,
	remarks_wdi varchar(300) NULL,
	mnp_process_date timestamp(6) NULL,
	timeallottment timestamp(6) NULL,
	in_status varchar(15) NULL,
	inserted_time timestamp(6) DEFAULT CURRENT_TIMESTAMP NULL,
	final_act_update_time timestamp(6) NULL,
	pdf_submission varchar(60) NULL,
	csv_submission varchar(60) NULL,
	ss_group_id varchar(150) NULL,
	column1 varchar(60) NULL,
	column2 varchar(60) NULL,
	column3 varchar(60) NULL,
	column4 varchar(60) NULL,
	pwd varchar(9) NULL,
	photo bytea NULL,
	photo_aadhaar bytea NULL,
	verified_flag varchar NULL,
	unq_resp_code_pos varchar(50) NULL,
	unq_resp_code_cust varchar(50) NULL,
	unq_resp_date_pos timestamptz NULL,
	unq_resp_date_cust timestamptz NULL,
	verfied_date varchar NULL,
	verfied_by varchar NULL,
	photo_pos bytea NULL,
	device_ip varchar(30) NULL,
	device_mac varchar(50) NULL,
	onboarding_type varchar(30) NULL,
	verified_by varchar NULL,
	verified_date timestamptz NULL,
	latitude varchar(50) NULL,
	longitude varchar(50) NULL,
	app_version varchar(10) NULL,
	live_photo_time timestamptz NULL,
	rejection_reason varchar NULL,
	pos_adh_name varchar(150) NULL,
	subscriber_type varchar(50) DEFAULT 'local'::character varying NULL,
	pdf_caf_generated varchar(1) DEFAULT 'N'::character varying NULL,
	pdf_caf_signed varchar(1) DEFAULT 'N'::character varying NULL,
	local_ref_name varchar(150) NULL,
	ref_careof_address varchar(200) NULL,
	ref_landmark varchar(200) NULL,
	ref_district varchar(150) NULL,
	upcvalidupto timestamptz NULL,
	caf_type varchar(50) DEFAULT 'cymn'::character varying NULL,
	ref_otp varchar(10) NULL,
	ref_otp_time timestamptz NULL,
	mnp_connection_type int4 NULL,
	frc_plan_name varchar(200) NULL,
	frc_plan_code varchar(50) NULL,
	frc_category_code varchar(50) NULL,
	frc_ctopup_number varchar(50) NULL,
	frc_ctopup_number_mpin varchar(10) NULL,
	father_name_adh varchar(150) NULL,
	parent_ctopup_number varchar(20) NULL,
	in_process bool DEFAULT false NULL,
	process_by varchar(50) NULL,
	process_at timestamptz NULL,
	std_isd varchar(10) NULL,
	deposit_required varchar(5) NULL,
	no_deposit_reason varchar(100) NULL,
	payment_method varchar(50) NULL,
	amount_received varchar(50) NULL,
	postpaid_plan_name varchar(50) NULL,
	pwd_per_disability varchar(20) NULL,
	pos_aadhaar varchar(20) NULL,
	unique_id varchar(15) NULL,
	sim_ssa varchar(50) NULL,
	is_alternate_process_informed bool DEFAULT true NULL,
	is_voluntary_ekyc_selected bool DEFAULT true NULL,
	has_aadhaar_consent_given bool DEFAULT true NULL,
	ver_account_id int8 NULL,
	adh_token varchar(80) NULL,
	updated_ts timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT cos_bcd_caf_serial_no_unique UNIQUE (caf_serial_no)
);
CREATE INDEX cos_bcd_gsmnumber_idx ON public.cos_bcd USING btree (gsmnumber);
CREATE INDEX cos_bcd_rever_idx ON public.cos_bcd USING btree (gsmnumber, verified_date, verified_flag);
CREATE INDEX cos_bcd_rever_idx2 ON public.cos_bcd USING btree (gsmnumber, live_photo_time, verified_flag);
CREATE INDEX idx_cos_bcd_live_photo_time ON public.cos_bcd USING btree (live_photo_time, caf_type) WHERE (live_photo_time IS NOT NULL);
CREATE INDEX idx_cos_bcd_username_photo ON public.cos_bcd USING btree (de_username, live_photo_time) INCLUDE (verified_flag);
CREATE INDEX idx_ver_account_id ON public.cos_bcd USING btree (ver_account_id);

-- public.cos_bcd_dkyc definition

-- Drop table

-- DROP TABLE public.cos_bcd_dkyc;

CREATE TABLE public.cos_bcd_dkyc (
	id serial4 NOT NULL,
	de_csccode varchar(150) NULL,
	de_username varchar(150) NULL,
	circle_code varchar(20) NULL,
	ssa_code varchar(20) NULL,
	caf_serial_no varchar(20) NULL,
	connection_type varchar(50) NULL,
	sim_type varchar(20) NULL,
	subscriber_type varchar(50) NULL,
	nationality varchar(60) NULL,
	gsmnumber varchar(20) NULL,
	sim_no varchar(20) NULL,
	cust_mob_no varchar(20) NULL,
	customer_otp varchar(10) NULL,
	customer_otp_time timestamptz NULL,
	customer_otp_relation varchar(20) NULL,
	tariff_plan varchar(100) NULL,
	parent_ctopup_number varchar(20) NULL,
	mpin varchar(10) NULL,
	subscriber_name varchar(200) NULL,
	pwd_status varchar(10) NULL,
	father_husband_name varchar(200) NULL,
	gender varchar(20) NULL,
	date_of_birth timestamp NULL,
	jio_count int4 NULL,
	airtel_count int4 NULL,
	vi_count int4 NULL,
	bsnl_count int4 NULL,
	other_count int4 NULL,
	corr_relation_type varchar(50) NULL,
	corr_relation_name varchar(150) NULL,
	corr_house_details varchar(150) NULL,
	corr_street_address varchar(150) NULL,
	corr_landmark varchar(150) NULL,
	corr_area_locality varchar(150) NULL,
	corr_city varchar(100) NULL,
	corr_district varchar(100) NULL,
	corr_state_ut varchar(100) NULL,
	corr_pin_code varchar(10) NULL,
	perm_relation_type varchar(50) NULL,
	perm_relation_name varchar(150) NULL,
	perm_house_details varchar(150) NULL,
	perm_street_address varchar(150) NULL,
	perm_landmark varchar(150) NULL,
	perm_area_locality varchar(150) NULL,
	perm_city varchar(100) NULL,
	perm_district varchar(100) NULL,
	perm_state_ut varchar(100) NULL,
	perm_pin_code varchar(10) NULL,
	value_added_services varchar(150) NULL,
	email_address varchar(150) NULL,
	profession varchar(100) NULL,
	pan_gir varchar(20) NULL,
	alt_home_number varchar(15) NULL,
	alt_business_number varchar(15) NULL,
	alt_mobile_number varchar(15) NULL,
	poi_type varchar(50) NULL,
	poi_number varchar(50) NULL,
	poi_date_of_issue timestamp NULL,
	poi_place_of_issue varchar(100) NULL,
	poi_issue_authority varchar(100) NULL,
	poa_type varchar(50) NULL,
	poa_number varchar(50) NULL,
	poa_date_of_issue timestamp NULL,
	poa_place_of_issue varchar(100) NULL,
	poa_issue_authority varchar(100) NULL,
	pos_declaration_check bool NULL,
	declaration1 bool NULL,
	declaration2 bool NULL,
	declaration3 bool NULL,
	poi_document_front varchar(255) NULL,
	poi_document_back varchar(255) NULL,
	poa_document_front varchar(255) NULL,
	poa_document_back varchar(255) NULL,
	customer_photo varchar(255) NULL,
	pos_photo varchar(255) NULL,
	pos_otp varchar(10) NULL,
	pos_otp_gen_time timestamptz NULL,
	pos_otp_ver_time timestamptz NULL,
	pos_lat varchar(20) NULL,
	pos_lang varchar(20) NULL,
	cust_lat varchar(20) NULL,
	cust_lang varchar(20) NULL,
	upc_code varchar(30) NULL,
	upcvalidupto timestamptz NULL,
	prev_optr varchar(60) NULL,
	prev_optr_area varchar(60) NULL,
	payment_mode varchar(60) NULL,
	std_isd varchar(10) NULL,
	deposit_required varchar(5) NULL,
	no_deposit_reason varchar(100) NULL,
	payment_method varchar(50) NULL,
	amount_received varchar(50) NULL,
	postpaid_plan_name varchar(50) NULL,
	outstation_ref_name varchar(200) NULL,
	outstation_mob_no varchar(20) NULL,
	outstation_address varchar(350) NULL,
	device_ip varchar(30) NULL,
	device_mac varchar(50) NULL,
	verified_flag varchar(5) NULL,
	verified_by varchar NULL,
	verified_date timestamptz NULL,
	app_version varchar(10) NULL,
	rejection_reason varchar NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	outstation_otp_gen_time timestamptz NULL,
	outstation_otp_ver_time timestamptz NULL,
	outstation_otp_code varchar(20) NULL,
	ins_usr varchar(300) NULL,
	in_process bool NULL,
	in_status varchar(15) NULL,
	caf_type varchar(20) NULL,
	process_by varchar(200) NULL,
	bank_account_no varchar(50) NULL,
	ifsc_code varchar(20) NULL,
	bank_name varchar(100) NULL,
	bank_branch varchar(100) NULL,
	type_disability varchar(100) NULL,
	pwd_per_disability varchar(20) NULL,
	pwd_doc_photo varchar(200) NULL,
	category varchar(25) NULL,
	cug_owner_name varchar(50) NULL,
	auth_per_desig varchar(50) NULL,
	cug_reference_id varchar NULL,
	cug_group_id varchar(30) NULL,
	customer_type varchar(25) DEFAULT 'Individual'::character varying NULL,
	master_child varchar(10) NULL,
	master_account_no varchar(50) NULL,
	authorisation_letter varchar(255) NULL,
	cug_group_details_photo varchar(255) NULL,
	customer_photo_time timestamptz NULL,
	pos_photo_time timestamptz NULL,
	poi_document_front_time timestamptz NULL,
	poi_document_back_time timestamptz NULL,
	poa_document_front_time timestamptz NULL,
	poa_document_back_time timestamptz NULL,
	imsi varchar(100) NULL,
	imsi_type varchar(50) NULL,
	unique_id varchar(150) NULL,
	company_name varchar(100) NULL,
	billing_address varchar(255) NULL,
	simstate varchar(45) NULL,
	sim_ssa varchar(45) NULL,
	auth_letter_document_number varchar(100) NULL,
	auth_letter_issue_authority varchar(100) NULL,
	unique_response_code varchar(100) NULL,
	unique_response_time varchar(50) NULL,
	aadhaar_photo varchar(300) NULL,
	cust_video varchar(300) NULL,
	skyc_reference varchar(100) NULL,
	cust_unique_id varchar(70) NULL,
	reverify_trans_id varchar(50) NULL,
	ver_account_id int8 NULL,
	reserve_status varchar NULL,
	sansad varchar NULL,
	frc_plan_name varchar(200) NULL,
	frc_plan_code varchar(50) NULL,
	frc_category_code varchar(50) NULL,
	frc_ctopup_number varchar(50) NULL,
	frc_ctopup_number_mpin varchar(10) NULL,
	tid varchar(60) NULL,
	om_remarks varchar(300) NULL,
	adh_token varchar(200) NULL,
	updated_ts timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT cos_bcd_dkyc_pkey1 PRIMARY KEY (id)
);
CREATE INDEX cos_bcd_dkyc_caf_serial_no_idx ON public.cos_bcd_dkyc USING btree (caf_serial_no);
CREATE INDEX cos_bcd_dkyc_caf_type_idx ON public.cos_bcd_dkyc USING btree (caf_type);
CREATE INDEX cos_bcd_dkyc_circle_code_idx ON public.cos_bcd_dkyc USING btree (circle_code);
CREATE INDEX cos_bcd_dkyc_created_at_idx ON public.cos_bcd_dkyc USING btree (created_at);
CREATE INDEX cos_bcd_dkyc_gsmnumber_idx ON public.cos_bcd_dkyc USING btree (gsmnumber);
CREATE INDEX cos_bcd_dkyc_rever_idx ON public.cos_bcd_dkyc USING btree (gsmnumber, verified_date, verified_flag);
CREATE INDEX cos_bcd_dkyc_ssa_code_idx ON public.cos_bcd_dkyc USING btree (ssa_code);
CREATE INDEX cos_bcd_dkyc_verified_flag_idx ON public.cos_bcd_dkyc USING btree (verified_flag);
CREATE INDEX idx_cos_bcd_dkyc_username_created ON public.cos_bcd_dkyc USING btree (de_username, created_at) INCLUDE (verified_flag);

-- public.ctop_master definition

-- Drop table

-- DROP TABLE public.ctop_master;

CREATE TABLE public.ctop_master (
	username varchar(30) NULL,
	ctopupno varchar(20) NULL,
	"name" varchar(100) NULL,
	dealertype varchar(50) NULL,
	ssa_code varchar(50) NULL,
	csccode varchar(100) NULL,
	circle_code varchar(10) NULL,
	attached_to varchar(50) NULL,
	contact_number varchar(50) NULL,
	pos_hno varchar(100) NULL,
	pos_street varchar(100) NULL,
	pos_landmark varchar(100) NULL,
	pos_locality varchar(100) NULL,
	pos_city varchar(100) NULL,
	pos_district varchar(100) NULL,
	pos_state varchar(100) NULL,
	pos_pincode varchar(100) NULL,
	created_date timestamp NULL,
	pos_name_ss varchar(100) NULL,
	pos_owner_name varchar(100) NULL,
	pos_code varchar(100) NULL,
	pos_ctop varchar(100) NOT NULL,
	circle_name varchar(50) NULL,
	pos_unique_code varchar(50) NOT NULL,
	latitude text NULL,
	longitude text NULL,
	aadhaar_no varchar(20) NULL,
	zone_code varchar(5) NULL,
	ctop_type varchar(50) DEFAULT 'DIRECT'::character varying NOT NULL,
	given_by varchar(2) NULL,
	swap_allowed varchar(2) DEFAULT 'N'::character varying NULL,
	swap_allowed_time timestamptz NULL,
	swap_allowed_user varchar(100) NULL,
	aggrement_through varchar(30) NULL,
	remark varchar(100) NULL,
	data_source varchar(50) NULL,
	account_id int8 NULL,
	updated_on timestamp NULL,
	created_on timestamp NULL,
	dealer_id numeric NULL,
	dealercode varchar(50) NULL,
	active varchar(1) NULL,
	ref_dealer_id numeric NULL,
	master_dealer_id numeric NULL,
	parent_ctopno varchar(50) NULL,
	dealer_status varchar(50) NULL,
	start_date timestamptz NULL,
	end_date timestamptz NULL,
	unique_id varchar(15) DEFAULT (('ct'::text || lpad(nextval('ctop_master_unique_id_seq'::regclass)::text, 13, '0'::text))) NOT NULL,
	previous_pos_unique_code text NULL,
	home_latitude text NULL,
	home_longitude text NULL,
	decsccode varchar(20) NULL,
	agreement_type varchar(50) NULL,
	nesl_done varchar(1) DEFAULT 'P'::character varying NULL,
	user_role varchar(20) NULL,
	updated_by int8 NULL,
	aadhaar_name text NULL,
	CONSTRAINT circle_code_is_valid CHECK (((circle_code IS NULL) OR ((circle_code)::text ~ '^[0-9]{1,2}$'::text))),
	CONSTRAINT ctop_master_pkey PRIMARY KEY (unique_id),
	CONSTRAINT ctop_master_pos_unique_code_pos_ctop_key UNIQUE (pos_unique_code, pos_ctop),
	CONSTRAINT ctop_master_username_unique UNIQUE (username),
	CONSTRAINT ctop_unique_id_length_check CHECK ((length((unique_id)::text) = 15))
);
CREATE INDEX ctop_master_attached_to_idx ON public.ctop_master USING btree (attached_to);
CREATE INDEX idx_ctop_master_ctopupno_dealertype ON public.ctop_master USING btree (ctopupno, dealertype);
CREATE INDEX idx_ctop_master_uid ON public.ctop_master USING btree (unique_id);
CREATE INDEX idx_ctop_master_username ON public.ctop_master USING btree (username);

-- public.ctop_master_delta definition

-- Drop table

-- DROP TABLE public.ctop_master_delta;

CREATE TABLE public.ctop_master_delta (
	ctopupno varchar(15) NULL,
	"name" varchar(50) NULL,
	dealertype varchar(50) NULL,
	dealer_id numeric NULL,
	dealercode varchar(50) NULL,
	issuedate timestamp NULL,
	cityid numeric NULL,
	ssa_code varchar(50) NULL,
	circle_code numeric(2) NULL,
	csccode varchar(50) NULL,
	attached_to varchar(50) NULL,
	active bpchar(1) NULL,
	deact_date timestamp NULL,
	ssa_city varchar(50) NULL,
	ref_dealer_id numeric NULL,
	master_dealer_id numeric NULL,
	functional bpchar(1) NULL,
	sms_act varchar(50) NULL,
	parent_ctopno varchar(15) NULL,
	contact_number varchar(50) NULL,
	second_name varchar(30) NULL,
	last_name varchar(30) NULL,
	dealer_address varchar(255) NULL,
	dealer_status varchar(15) NULL,
	aadhaar_no varchar(20) NULL,
	zone_code varchar(5) NULL,
	created_datetime timestamptz NULL,
	modified_date timestamptz NULL
);

-- public.frc_plan_table definition

-- Drop table

-- DROP TABLE public.frc_plan_table;

CREATE TABLE public.frc_plan_table (
	id serial4 NOT NULL,
	plan_name varchar(200) NOT NULL,
	plan_code varchar(50) NOT NULL,
	category_code varchar(50) NOT NULL,
	start_date date NOT NULL,
	end_date date NULL,
	circle_code varchar(10) NOT NULL,
	frc_amount numeric(6) NOT NULL,
	CONSTRAINT frc_plan_table_pkey PRIMARY KEY (id)
);

-- public.frc_pyro_request_data definition

-- Drop table

-- DROP TABLE public.frc_pyro_request_data;

CREATE TABLE public.frc_pyro_request_data (
	reqid bigserial NOT NULL,
	client_txn_id varchar(15) NULL,
	caf_serial_no varchar(30) NOT NULL,
	gsmno varchar(10) NOT NULL,
	csccode varchar(50) NULL,
	circle_code int2 NULL,
	kyc_mode varchar(5) NOT NULL,
	edate date NOT NULL,
	frc_plan_name varchar(100) NULL,
	frc_plan_code varchar(50) NOT NULL,
	frc_category_code varchar(50) NOT NULL,
	frcamt int4 NOT NULL,
	reqdate timestamptz NULL,
	ctopup_number varchar(10) NOT NULL,
	vendormsisdn varchar(10) NULL,
	vendorid varchar(50) NULL,
	mpin varchar(200) NOT NULL,
	mpin_length int2 NULL,
	in_status varchar(3) DEFAULT 'C'::character varying NOT NULL,
	pyro_status varchar(3) DEFAULT 'N'::character varying NOT NULL,
	push_flag varchar(1) DEFAULT 'N'::character varying NOT NULL,
	push_remarks varchar(200) NULL,
	push_date timestamptz NULL,
	batch_date date DEFAULT CURRENT_DATE NOT NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	pyro_trans_id int8 NULL,
	pyro_initial_statuscode int4 NULL,
	submitted_at timestamptz NULL,
	msg2pyro text NULL,
	msg_afterreq text NULL,
	callback_received_at timestamptz NULL,
	dealer_bal_before numeric(12, 2) NULL,
	dealer_bal_after numeric(12, 2) NULL,
	subscriber_circle varchar(50) NULL,
	msg_aftertr text NULL,
	replymsg varchar(200) NULL,
	replyrecvd_date timestamptz NULL,
	status_check_eligible_at timestamptz NULL,
	status_check_count int2 DEFAULT 0 NOT NULL,
	last_status_check_at timestamptz NULL,
	final_status varchar(10) NULL,
	pyro_final_statuscode int4 NULL,
	completed_at timestamptz NULL,
	retry_count int2 DEFAULT 0 NOT NULL,
	max_retries int2 DEFAULT 3 NOT NULL,
	last_error_code varchar(10) NULL,
	last_error_msg varchar(500) NULL,
	seller_comm numeric NULL,
	fra_comm numeric NULL,
	ipdetail varchar(20) NULL,
	remarks varchar(500) NULL,
	updated_ts timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT frc_pyro_final_chk CHECK (((final_status IS NULL) OR ((final_status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying])::text[])))),
	CONSTRAINT frc_pyro_in_status_chk CHECK (((in_status)::text = ANY ((ARRAY['C'::character varying, 'S'::character varying, 'F'::character varying])::text[]))),
	CONSTRAINT frc_pyro_kyc_chk CHECK (((kyc_mode)::text = ANY ((ARRAY['EKYC'::character varying, 'DKYC'::character varying, 'SKYC'::character varying])::text[]))),
	CONSTRAINT frc_pyro_pk PRIMARY KEY (reqid),
	CONSTRAINT frc_pyro_push_flag_chk CHECK (((push_flag)::text = ANY ((ARRAY['N'::character varying, 'P'::character varying, 'Y'::character varying, 'F'::character varying, 'E'::character varying])::text[]))),
	CONSTRAINT frc_pyro_pyro_status_chk CHECK (((pyro_status)::text = ANY ((ARRAY['N'::character varying, 'REG'::character varying, 'SUC'::character varying, 'FAL'::character varying])::text[]))),
	CONSTRAINT frc_pyro_retry_chk CHECK ((retry_count <= (max_retries + 1))),
	CONSTRAINT frc_pyro_uq_batch_caf UNIQUE (batch_date, caf_serial_no)
);
CREATE INDEX idx_frc_pyro_caf ON public.frc_pyro_request_data USING btree (caf_serial_no, batch_date);
CREATE INDEX idx_frc_pyro_final ON public.frc_pyro_request_data USING btree (final_status, completed_at) WHERE (final_status IS NOT NULL);
CREATE INDEX idx_frc_pyro_gsmno ON public.frc_pyro_request_data USING btree (gsmno);
CREATE INDEX idx_frc_pyro_pickup ON public.frc_pyro_request_data USING btree (push_flag, batch_date, created_at);
CREATE INDEX idx_frc_pyro_status_check ON public.frc_pyro_request_data USING btree (status_check_eligible_at, push_flag) WHERE ((push_flag)::text = 'P'::text);
CREATE INDEX idx_frc_pyro_trans_id ON public.frc_pyro_request_data USING btree (pyro_trans_id) WHERE (pyro_trans_id IS NOT NULL);